---
- name: database setup
  hosts: localhost
  become: true
  tasks:

    - name: Repository Python
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
      
    - name: Install python3.6
      apt: name=python state=present

    - name: Check if Redis exists
      stat:
        path: "/etc/redis"
      register: result

    - name: Get and Prepare redis
      shell: curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
      shell: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
      when: not result.stat.exists

    - name: Install redis
      apt: name=redis state=present
      when: not result.stat.exists